- name: Gathering facts
  setup: { }
- name: Package count
  shell: wc -l /etc/apk/world | cut -d ' ' -f 1
  register: result
  changed_when: false

- set_fact:
    package_count: "{{ result.stdout }}"

- name: OS Info
  debug:
    msg:
    - "{{ ansible_user_id }}({{ ansible_user_uid }})@{{ ansible_nodename }}"
    - "OS: {{ ansible_os_family }} {{ ansible_distribution_version }} {{ ansible_osversion|default('-')}}/{{ansible_osrevision|default('-') }} {{ ansible_machine }}"
    - "Host: {{ ansible_model | default(ansible_product_name) | default(ansible_system_vendor) }}"
    - "Ansible inventory: {{ inventory_hostname }} ,host: {{ ansible_host }}"
    - "CPU: {{ ansible_processor_count|default('-') }}x{{ ansible_processor_cores }}Cx{{ ansible_processor_threads_per_core|default('-') }}T={{ ansible_processor_vcpus }} vcpu {{ (ansible_processor[2]|length > 1)|ternary(ansible_processor[2],ansible_processor) }}"
    - "Memory: {{ ansible_memtotal_mb - ansible_memfree_mb }} MB / {{ ansible_memtotal_mb }} MB"
    - "Kernel: {{ ansible_kernel }}"
    - "Uptime: {{ (ansible_uptime_seconds|default(0)/60/60/24)|int }} days {{ (ansible_uptime_seconds|default(0)/60/60 % 24)|int}} hours {{(ansible_uptime_seconds|default(0)/60 % 60)|int }} minutes"
    - "Packages: {{ package_count }} ({{ ansible_pkg_mgr }})"
    - "Shell: {{ ansible_user_shell }}"
    - "Network: {% if ansible_default_ipv4 is defined %}{{ ansible_default_ipv4.interface }} {{ ansible_default_ipv4.address }} {{ ansible_default_ipv4.netmask }}{% else %}n/a{% endif %}"
    - "DNS: {{ ' '.join(ansible_dns.nameservers|default('-')) }}"
    - "Python: {{ ansible_python.executable }} {{ ansible_python_version }}"
    - "Interfaces: {% if ansible_interfaces is defined %}{{ ', '.join(ansible_interfaces|sort) }}{% else %}n/a{% endif %}"
    - "Addresses: {% if ansible_all_ipv4_addresses is defined %}{{ ', '.join(ansible_all_ipv4_addresses|sort) }}{% else %}n/a{% endif %}"
