# setup gateway interface

- name: install packages
  become: true
  apk:
    name: '{{ item }}'
  loop:
    - iproute2
    - bridge
    - iptables


- name: setup interface
  set_fact:
    gateway_in_interface: "{{ gateway_in_interface|default('eth0') }}"
    gateway_out_interface: "{{ gateway_out_interface|default('eth0') }}"
    gateway_source: "{{ gateway_source|default('0.0.0.0/0') }}"
    gateway_destination: "{{ gateway_destination|default('0.0.0.0/0') }}"
    gateway_persist: "{{ gateway_persist|default(true) }}"

- name: sysctl conf
  become: true
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: net.ipv4.ip_forward, value: 1 }

# iptables -I FORWARD -i eth0 -j ACCEPT
# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

- name: enable forward
  become: true
  iptables:
    in_interface: "{{ gateway_in_interface }}"
    source: "{{ gateway_source }}"
    destination: "{{ gateway_destination }}"
    action: insert
    chain: FORWARD
    jump: ACCEPT

- name: enable nat
  become: true
  iptables:
    out_interface: "{{ gateway_out_interface }}"
    source: "{{ gateway_source }}"
    destination: "{{ gateway_destination }}"
    action: append
    table: nat
    chain: POSTROUTING
    jump: MASQUERADE

- name: persist forward conf
  become: true
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ gateway_in_interface }}"
    option: post-up
    value: iptables -I FORWARD -i {{ gateway_in_interface }} -s {{ gateway_source }} -d {{ gateway_destination }} -j ACCEPT
    state: present
  when: gateway_persist

- name: persist nat conf
  become: true
  interfaces_file:
    dest: /etc/network/interfaces
    iface: "{{ gateway_in_interface }}"
    option: post-up
    value: iptables -t nat -A POSTROUTING -o {{ gateway_out_interface }} -s {{ gateway_source }} -d {{ gateway_destination }} -j MASQUERADE
    state: present
  when: gateway_persist
