## ip-rout-add
# dry_run - print command
# prefix - the network to route
# via - nexthop device router
# device - output device
# metric
# table
# source_address
# tos

- name: ip route add
  shell: >-
    [
    0 = $(ip route show {{ prefix }} | wc -l)
    ] && (
    {{ 'echo ' if dry_run is defined else '' }}
    ip route add
    to {{ type if type is defined else 'unicast' }} {{ prefix }}
    {{ 'tos '+tos if tos is defined else "" }}
    {{ "metric "+metric if metric is defined else "" }}
    {{ "table "+table if table is defined else "" }}
    via {{ via }}
    {{ 'dev '+device if device is defined else "" }}
    {{ "src "+source_address if source_address is defined else "" }}
    {{ '>&2 ' if dry_run is defined else '' }}
    ; echo -n 0
    ) || echo -n 1
  register: shell_out
  failed_when: shell_out.stdout not in ['0','1']
  changed_when: shell_out.stdout == '0'

- name: dry run command
  debug:
    msg: "{{ shell_out.stderr }}"
  when: dry_run is defined
