- name: prometheus | Install
  become: true
  package:
    name: prometheus
    state: present

- name: prometheus | inline string conf
  become: true
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: "{{ prometheus_conf_inline }}"
  when: prometheus_conf_inline is defined and prometheus_conf_inline is string
# todo handle changes

- name: prometheus | inline mapping conf
  become: true
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: "{{ prometheus_conf_inline | to_yaml }}"
  when: prometheus_conf_inline is defined and prometheus_conf_inline is mapping
  notify: prometheus-reload

- name: prometheus | service inline conf
  become: true
  copy:
    dest: /etc/conf.d/prometheus
    content: "{{ prometheus_service_conf_inline }}"
    mode: preserve
  when: prometheus_service_conf_inline is defined and prometheus_conf_inline is string
  notify: prometheus-reload

# map conf
# prometheus_service_conf = [{name,value}]
